"""empty message

Revision ID: 373d9cc220aa
Revises: 7e1222736041
Create Date: 2020-05-05 03:57:46.532589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '373d9cc220aa'
down_revision = '7e1222736041'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
